services:
  redis:
    image: redis:7-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - scraper_network

  worker:
    build:
      context: ./scraping module
    container_name: scraper_worker
    working_dir: /app
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    networks:
      - scraper_network
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./scraping module:/app

  backend:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-exclude "__pycache__"
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    networks:
      - scraper_network
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:14-alpine
    container_name: postgres_service
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scraper_network

  ml_worker:
    build:
      context: ./backend
    command: celery -A tasks worker --loglevel=info -Q ml_tasks --concurrency=4
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - scraper_network
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./backend:/app

volumes:
  pgdata:


networks:
  scraper_network:
    driver: bridge
