services:
  redis:
    image: redis:7-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - scraper_network

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    networks:
      - scraper_network
    volumes:
      - .:/app

networks:
  scraper_network:
    driver: bridge